export const AUTH_USER = 'AUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_CURRENT_USER = 'AUTH_CURRENT_USER';

export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const PRODUCTS_ERROR = 'PRODUCTS_ERROR';

export const FETCH_PRODUCT = 'FETCH_PRODUCT';
export const PRODUCT_ERROR = 'PRODUCT_ERROR';

export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';

export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS';
export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD';

export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';

export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL';
export const ORDER_CREATE_DETAILS = 'ORDER_CREATE_DETAILS';
export const ORDER_DETAILS_ERROR = 'ORDER_DETAILS_ERROR';

export const ORDER_PAY_DETAILS = 'ORDER_PAY_DETAILS';
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET';
export const ORDER_PAY_ERROR = 'ORDER_PAY_ERROR';

export const ORDER_LIST_DETAILS = 'ORDER_LIST_DETAILS';
export const ORDER_LIST_ERROR = 'ORDER_LIST_ERROR';
export const ORDER_LIST_RESET = 'ORDER_LIST_RESET';

export const FETCH_WISHLIST_DETAILS = 'FETCH_WISHLIST_DETAILS';
export const FETCH_WISHLIST_ERROR = 'FETCH_WISHLIST_ERROR';
export const FETCH_WISHLIST_LOADING = 'FETCH_WISHLIST_LOADING';
